# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_ROOT: ${{ github.workspace }}/examples
  TF_STATE_NAME: git-s3-lfs

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
            terraform init 
            terraform validate 
            terraform plan
        working-directory: ${{ env.TF_ROOT }}

  test:
    runs-on: ubuntu-latest
    env:
      TF_ROOT: ${{ github.workspace }}/tests
      TF_STATE_NAME: git-s3-lfs-tests
    services:
      localstack:
        image: localstack/localstack:1.4
        ports:
          - 4566:4566
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Exsisting Bucket and Users
        run: |
          terraform init
          terraform plan -var-file=../vars/git.tfvars
        working-directory: ${{ env.TF_ROOT }}/exsisting-bucket-and-users
      
      - name: Exsisting Bucket and new Users
        run: |
          terraform init
          terraform plan -var-file=../vars/git.tfvars
        working-directory: ${{ env.TF_ROOT }}/exsisting-bucket-new-users
      
      - name: Exsisting Bucket and mix Users
        run: |
          terraform init
          terraform plan -var-file=../vars/git.tfvars
        working-directory: ${{ env.TF_ROOT }}/exsisting-bucket-mix-users
      
      - name: New Bucket and exsisting Users
        run: |
          terraform init
          terraform plan -var-file=../vars/git.tfvars
        working-directory: ${{ env.TF_ROOT }}/new-bucket-exsisting-users
      
      - name: New Bucket and new Users
        run: |
          terraform init
          terraform plan -var-file=../vars/git.tfvars
        working-directory: ${{ env.TF_ROOT }}/new-bucket-new-users

      - name: New Bucket and mix Users
        run: |
          terraform init
          terraform plan -var-file=../vars/git.tfvars
        working-directory: ${{ env.TF_ROOT }}/new-bucket-mix-users
